# pnpm workspace設定
packages:
  # メインアプリケーション
  - '.'
  
  # スクリプト用パッケージ（将来的に分離する場合）
  - 'scripts'
  
  # ドキュメント（将来的に追加する場合）
  - 'docs'
  
  # 共有パッケージ（将来的に追加する場合） 
  - 'packages/*'
  
  # テスト関連（将来的に追加する場合）
  - 'tests'
