name = "test-website"
compatibility_date = "2024-07-31"
compatibility_flags = ["nodejs_compat"]

# Pages設定（Next.jsアプリ用）
[env.production]
account_id = "your-account-id"
zone_id = "your-zone-id"

# 環境変数
[env.production.vars]
NODE_ENV = "production"
# MongoDB Atlas接続文字列
MONGODB_URI = "mongodb+srv://jungamer64:Ib9zZjRzzV9iZU0z@website.maxtfuo.mongodb.net/test-website?retryWrites=true&w=majority&appName=Website"
# JWT設定（本番用は別の値に変更してください）
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"

# KV Namespace（必要に応じて）
# [[env.production.kv_namespaces]]
# binding = "test-website"
# id = "4bc93e34a53743689076881dd162389e"

# D1 Database（MongoDBの代わりにCloudflare D1を使用する場合）
# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "test-website"
# database_id = "5fdea03d-3fd3-455f-9d32-b4218a1c5e0d"
